# Uncomment the next line to define a global platform for your project
platform :ios, '14'

target 'Scanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Scanner
  pod 'Alamofire', '~> 5.2'
  pod 'WeScan', '>= 0.9'
  pod "ESTabBarController-swift"

  target 'ScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScannerUITests' do
    # Pods for testing
  end

end
